import React, { createContext, useContext, useState, useEffect } from "react";
import AsyncStorage from "@react-native-async-storage/async-storage";

type Lang = "hi" | "en";

export const TRANSLATIONS = {
  hi: {
    home: "होम",
    wallet: "वॉलेट",
    schedule: "शेड्यूल",
    profile: "प्रोफाइल",
    history: "हिस्ट्री",
    where_going: "कहाँ जाना है?",
    book_ride: "राइड बुक करें",
    schedule_ride: "राइड शेड्यूल करें",
    wallet_balance: "वॉलेट बैलेंस",
    add_money: "पैसे जोड़ें",
    withdraw: "निकालें",
    earnings: "कमाई",
    kyc_documents: "KYC दस्तावेज़",
    upload_docs: "दस्तावेज़ अपलोड करें",
    driver_mode: "ड्राइवर मोड",
    go_online: "ऑनलाइन जाएं",
    go_offline: "ऑफलाइन जाएं",
    earnings_today: "आज की कमाई",
    total_rides: "कुल राइड्स",
    language: "भाषा",
    hindi: "हिंदी",
    english: "English",
    cancel: "रद्द करें",
    confirm: "पुष्टि करें",
    submit: "जमा करें",
    pending: "लंबित",
    approved: "स्वीकृत",
    rejected: "अस्वीकृत",
    min_amount: "न्यूनतम राशि ₹100",
    topup_success: "वॉलेट टॉप-अप सफल!",
    ride_booked: "राइड बुक हो गई!",
    scheduled_for: "के लिए शेड्यूल",
    no_scheduled: "कोई शेड्यूल राइड नहीं",
    aadhaar_front: "आधार फ्रंट",
    aadhaar_back: "आधार बैक",
    license_front: "लाइसेंस फ्रंट",
    license_back: "लाइसेंस बैक",
    rc_book: "RC बुक",
    selfie: "सेल्फी",
    kyc_pending: "KYC समीक्षाधीन",
    kyc_verified: "KYC सत्यापित ✅",
    kyc_rejected: "KYC अस्वीकृत ❌",
    withdrawal_method: "निकासी का तरीका",
    bank_account: "बैंक खाता",
    enter_upi: "UPI ID दर्ज करें",
    enter_account: "खाता नंबर दर्ज करें",
    commission_info: "6.7% कमीशन काटकर",
    your_share: "आपका हिस्सा 93.3%",
    good_morning: "शुभ प्रभात 🌅",
    good_afternoon: "शुभ दोपहर ☀️",
    good_evening: "शुभ संध्या 🌆",
    good_night: "शुभ रात्रि 🌙",
    quick_select: "जल्दी चुनें",
    recent_rides: "हाल की राइड्स",
    search_dest: "गंतव्य खोजें...",
    suggestion_office: "ऑफिस",
    suggestion_office_sub: "कनॉट प्लेस",
    suggestion_home: "घर",
    suggestion_home_sub: "सेक्टर 62, नोएडा",
    suggestion_airport: "एयरपोर्ट",
    suggestion_airport_sub: "T3, IGI एयरपोर्ट",
    profile_update: "प्रोफाइल अपडेट",
    pickup_location: "पिकअप लोकेशन",
    save: "सेव करें",
    logout: "लॉगआउट",
    remove: "हटाएं",
    name_label: "नाम",
    email_optional: "ईमेल (वैकल्पिक)",
    name_placeholder: "अपना नाम लिखें",
    pickup_placeholder: "जैसे — कनॉट प्लेस, नई दिल्ली",
    gps_label: "GPS से वर्तमान स्थान उपयोग करें",
    set_pickup: "📍 पिकअप सेट करें",
    enter_address: "अपना पिकअप पता टाइप करें",
    use_on_ride: "राइड पे उपयोग करें",
    recent_dlf: "DLF साइबर हब",
    recent_lajpat: "लाजपत नगर मार्केट",
    recent_hauz: "हौज खास विलेज",
    online: "ऑनलाइन",
    offline: "ऑफलाइन",
    go_offline_btn: "ऑफलाइन जाएं",
    go_online_btn: "ऑनलाइन जाएं",
    // Wallet
    your_wallet: "आपका RaftaarRide वॉलेट",
    use_for_ride: "किसी भी राइड में उपयोग करें",
    use_on_ride_btn: "राइड पे उपयोग करें",
    use_on_ride_title: "राइड करें",
    use_on_ride_body: "वॉलेट से पेमेंट राइड में ऑटो-डेडक्ट होती है",
    recharge_wallet: "💳 वॉलेट रिचार्ज करें",
    select_quick_amt: "जल्दी राशि चुनें:",
    custom_amount: "या कस्टम राशि डालें (₹10 – ₹50,000):",
    choose_method: "पेमेंट तरीका चुनें:",
    enter_upi_label: "UPI ID डालें:",
    card_number: "कार्ड नंबर:",
    expiry_label: "एक्सपायरी (MM/YY):",
    account_number_label: "खाता नंबर:",
    ifsc_code: "IFSC कोड:",
    processing: "प्रोसेस हो रहा है...",
    processing_payment: "पेमेंट प्रोसेस हो रही है...",
    please_wait: "कृपया प्रतीक्षा करें",
    payment_success: "पेमेंट सफल!",
    added_to_wallet: "वॉलेट में जोड़ दिया गया",
    transaction_history: "लेन-देन इतिहास",
    no_transactions: "अभी तक कोई लेन-देन नहीं",
    upi_invalid: "UPI ID गलत है",
    card_invalid: "कार्ड नंबर गलत",
    expiry_invalid: "एक्सपायरी गलत",
    cvv_invalid: "CVV गलत",
    account_invalid: "खाता नंबर गलत",
    // Schedule
    advance_book: "पहले से राइड बुक करें",
    close: "बंद करें",
    new_scheduled: "नई शेड्यूल्ड राइड",
    ride_details: "राइड विवरण",
    pickup_location_ph: "पिकअप लोकेशन...",
    destination_ph: "गंतव्य...",
    date_label: "तारीख (YYYY-MM-DD):",
    time_label: "समय (HH:MM):",
    vehicle_type: "वाहन प्रकार:",
    special_instructions: "विशेष निर्देश (वैकल्पिक)...",
    scheduling: "शेड्यूल हो रहा है...",
    schedule_btn: "राइड शेड्यूल करें",
    no_scheduled_yet: "अभी तक कोई शेड्यूल राइड नहीं",
    use_btn_above: "ऊपर बटन से शेड्यूल करें",
    // Driver Mode
    new_ride: "नई राइड",
    accept: "स्वीकार करें",
    min_away: "मिनट दूर",
    // KYC
    kyc_subtitle: "ड्राइव करने के लिए दस्तावेज़ सत्यापित करवाएं",
    kyc_info: "📌 सभी 6 दस्तावेज़ अपलोड करना ज़रूरी है। दस्तावेज़ स्पष्ट और पढ़ने योग्य होने चाहिए। Max 500KB प्रति image.",
    added_label: "जोड़ा गया",
    kyc_is_verified: "KYC सत्यापित है",
    tap_to_upload: "टैप करके अपलोड करें",
    docs_uploaded: "दस्तावेज़ अपलोड किए",
    submitting: "सबमिट हो रहा है...",
    kyc_submit: "📋 KYC सबमिट करें",
    kyc_resubmit: "🔄 दस्तावेज़ पुनः सबमिट करें",
    verified_on: "सत्यापित:",
    // Earnings
    earnings_subtitle: "आपकी कमाई और निकासी",
    total_earned: "कुल कमाई (93.3%)",
    commission_label: "RaftaarRide कमीशन (6.7%)",
    withdrawable_balance: "निकासी योग्य बैलेंस",
    commission_note: "हर राइड से 6.7% कमीशन काटकर आपको 93.3% मिलता है",
    request_withdrawal: "निकासी अनुरोध करें",
    withdrawal_details: "निकासी विवरण",
    choose_amount: "राशि चुनें:",
    all: "सब",
    custom_amount_ph: "या कस्टम राशि...",
    you_receive: "आपको मिलेगा:",
    process_time: "24-48 घंटे में प्रोसेस होगी",
    withdrawal_submit: "💸 निकासी अनुरोध सबमिट करें",
    withdrawal_history: "📋 निकासी इतिहास",
    no_withdrawals: "अभी तक कोई निकासी अनुरोध नहीं",
    // Login
    login_welcome: "स्वागत है!",
    login_subtitle: "लॉगिन करके अपनी राइड बुक करो",
    login_otp_tab: "OTP से लॉगिन",
    login_email_tab: "ईमेल से लॉगिन",
    login_btn: "लॉगिन करें",
    no_account: "खाता नहीं है? रजिस्टर करें",
    // OTP
    otp_title: "OTP सत्यापित करें",
    otp_code_sent: "6-अंकीय कोड भेजा गया",
    otp_enter: "OTP डालें",
    otp_verify_btn: "सत्यापित करें",
    otp_resend_btn: "फिर भेजें",
    // Signup
    signup_title: "नया खाता बनाएं",
    signup_subtitle: "RaftaarRide का हिस्सा बनें",
    signup_btn: "खाता बनाएं",
    have_account: "खाता है? लॉगिन करें",
    // Driver Login
    driver_login_title: "ड्राइवर लॉगिन",
    driver_login_sub: "अपने खाते में लॉगिन करें",
    driver_login_btn: "लॉगिन करें",
    no_driver_acct: "खाता नहीं? रजिस्टर करें",
    // Driver Register
    driver_reg_title: "ड्राइवर रजिस्ट्रेशन",
    driver_reg_btn: "रजिस्टर करें",
    next_step: "आगे जाएं →",
    // Booking
    choose_vehicle: "वाहन चुनें",
    // LiveTracking
    tracking_title: "लाइव ट्रैकिंग",
    stage_pickup: "पिकअप पर",
    stage_riding: "राइड पर",
    stage_done: "पहुँच गए!",
  },
  en: {
    home: "Home",
    wallet: "Wallet",
    schedule: "Schedule",
    profile: "Profile",
    history: "History",
    where_going: "Where to?",
    book_ride: "Book Ride",
    schedule_ride: "Schedule Ride",
    wallet_balance: "Wallet Balance",
    add_money: "Add Money",
    withdraw: "Withdraw",
    earnings: "Earnings",
    kyc_documents: "KYC Documents",
    upload_docs: "Upload Documents",
    driver_mode: "Driver Mode",
    go_online: "Go Online",
    go_offline: "Go Offline",
    earnings_today: "Today's Earnings",
    total_rides: "Total Rides",
    language: "Language",
    hindi: "Hindi",
    english: "English",
    cancel: "Cancel",
    confirm: "Confirm",
    submit: "Submit",
    pending: "Pending",
    approved: "Approved",
    rejected: "Rejected",
    min_amount: "Minimum ₹100",
    topup_success: "Wallet top-up successful!",
    ride_booked: "Ride booked!",
    scheduled_for: "Scheduled for",
    no_scheduled: "No scheduled rides",
    aadhaar_front: "Aadhaar Front",
    aadhaar_back: "Aadhaar Back",
    license_front: "License Front",
    license_back: "License Back",
    rc_book: "RC Book",
    selfie: "Selfie",
    kyc_pending: "KYC Under Review",
    kyc_verified: "KYC Verified ✅",
    kyc_rejected: "KYC Rejected ❌",
    withdrawal_method: "Withdrawal Method",
    bank_account: "Bank Account",
    enter_upi: "Enter UPI ID",
    enter_account: "Enter Account Number",
    commission_info: "After 6.7% commission",
    your_share: "Your share is 93.3%",
    good_morning: "Good Morning 🌅",
    good_afternoon: "Good Afternoon ☀️",
    good_evening: "Good Evening 🌆",
    good_night: "Good Night 🌙",
    quick_select: "Quick Select",
    recent_rides: "Recent Rides",
    search_dest: "Search destination...",
    suggestion_office: "Office",
    suggestion_office_sub: "Connaught Place",
    suggestion_home: "Home",
    suggestion_home_sub: "Sector 62, Noida",
    suggestion_airport: "Airport",
    suggestion_airport_sub: "T3, IGI Airport",
    profile_update: "Profile Update",
    pickup_location: "Pickup Location",
    save: "Save",
    logout: "Logout",
    remove: "Remove",
    name_label: "Name",
    email_optional: "Email (optional)",
    name_placeholder: "Enter your name",
    pickup_placeholder: "e.g. Connaught Place, New Delhi",
    gps_label: "Use GPS current location",
    set_pickup: "📍 Set Pickup",
    enter_address: "Type your pickup address",
    use_on_ride: "Use on Ride",
    recent_dlf: "DLF Cyber Hub",
    recent_lajpat: "Lajpat Nagar Market",
    recent_hauz: "Hauz Khas Village",
    online: "Online",
    offline: "Offline",
    go_offline_btn: "Go Offline",
    go_online_btn: "Go Online",
    // Wallet
    your_wallet: "Your RaftaarRide Wallet",
    use_for_ride: "Use for any ride",
    use_on_ride_btn: "Use on Ride",
    use_on_ride_title: "Go Ride",
    use_on_ride_body: "Wallet balance is auto-deducted during rides",
    recharge_wallet: "💳 Recharge Wallet",
    select_quick_amt: "Select quick amount:",
    custom_amount: "Or enter custom amount (₹10 – ₹50,000):",
    choose_method: "Choose Payment Method:",
    enter_upi_label: "Enter UPI ID:",
    card_number: "Card Number:",
    expiry_label: "Expiry (MM/YY):",
    account_number_label: "Account Number:",
    ifsc_code: "IFSC Code:",
    processing: "Processing...",
    processing_payment: "Processing Payment...",
    please_wait: "Please wait",
    payment_success: "Payment Successful!",
    added_to_wallet: "Added to wallet",
    transaction_history: "Transaction History",
    no_transactions: "No transactions yet",
    upi_invalid: "Invalid UPI ID",
    card_invalid: "Invalid card number",
    expiry_invalid: "Invalid expiry",
    cvv_invalid: "Invalid CVV",
    account_invalid: "Invalid account number",
    // Schedule
    advance_book: "Book a ride in advance",
    close: "Close",
    new_scheduled: "New Scheduled Ride",
    ride_details: "Ride Details",
    pickup_location_ph: "Pickup location...",
    destination_ph: "Destination...",
    date_label: "Date (YYYY-MM-DD):",
    time_label: "Time (HH:MM):",
    vehicle_type: "Vehicle type:",
    special_instructions: "Special instructions (optional)...",
    scheduling: "Scheduling...",
    schedule_btn: "Schedule Ride",
    no_scheduled_yet: "No scheduled rides yet",
    use_btn_above: "Use the button above to schedule",
    // Driver Mode
    new_ride: "New Ride",
    accept: "Accept",
    min_away: "min away",
    // KYC
    kyc_subtitle: "Verify your documents to start driving",
    kyc_info: "📌 All 6 documents are required. Documents must be clear and readable. Max 500KB per image.",
    added_label: "Added",
    kyc_is_verified: "KYC is verified",
    tap_to_upload: "Tap to upload",
    docs_uploaded: "documents uploaded",
    submitting: "Submitting...",
    kyc_submit: "📋 Submit KYC",
    kyc_resubmit: "🔄 Resubmit Documents",
    verified_on: "Verified:",
    // Earnings
    earnings_subtitle: "Your earnings & withdrawals",
    total_earned: "Total Earned (93.3%)",
    commission_label: "Commission (6.7%)",
    withdrawable_balance: "Withdrawable Balance",
    commission_note: "After 6.7% commission, you keep 93.3% of each ride",
    request_withdrawal: "Request Withdrawal",
    withdrawal_details: "Withdrawal Details",
    choose_amount: "Choose amount:",
    all: "All",
    custom_amount_ph: "Or custom amount...",
    you_receive: "You'll receive:",
    process_time: "Will be processed in 24-48 hours",
    withdrawal_submit: "💸 Submit Withdrawal Request",
    withdrawal_history: "📋 Withdrawal History",
    no_withdrawals: "No withdrawal requests yet",
    // Login
    login_welcome: "Welcome!",
    login_subtitle: "Login to book your ride",
    login_otp_tab: "OTP Login",
    login_email_tab: "Email Login",
    login_btn: "Login",
    no_account: "No account? Register",
    // OTP
    otp_title: "Verify OTP",
    otp_code_sent: "6-digit OTP sent to",
    otp_enter: "Enter OTP",
    otp_verify_btn: "Verify",
    otp_resend_btn: "Resend",
    // Signup
    signup_title: "Create Account",
    signup_subtitle: "Join RaftaarRide",
    signup_btn: "Create Account",
    have_account: "Have account? Login",
    // Driver Login
    driver_login_title: "Driver Login",
    driver_login_sub: "Sign in to your account",
    driver_login_btn: "Login",
    no_driver_acct: "No account? Register",
    // Driver Register
    driver_reg_title: "Driver Registration",
    driver_reg_btn: "Register",
    next_step: "Next →",
    // Booking
    choose_vehicle: "Choose Vehicle",
    // LiveTracking
    tracking_title: "Live Tracking",
    stage_pickup: "At Pickup",
    stage_riding: "On Ride",
    stage_done: "Arrived!",
  },
} as const;

type TranslationKey = keyof typeof TRANSLATIONS.hi;

interface LanguageContextType {
  lang: Lang;
  t: (key: TranslationKey) => string;
  toggleLanguage: () => void;
  setLang: (l: Lang) => void;
}

const LanguageContext = createContext<LanguageContextType>({
  lang: "hi",
  t: (k) => TRANSLATIONS.hi[k],
  toggleLanguage: () => {},
  setLang: () => {},
});

const STORAGE_KEY = "raftaar_language";

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [lang, setLangState] = useState<Lang>("hi");

  useEffect(() => {
    AsyncStorage.getItem(STORAGE_KEY).then((v) => {
      if (v === "hi" || v === "en") setLangState(v);
    });
  }, []);

  const setLang = async (l: Lang) => {
    setLangState(l);
    await AsyncStorage.setItem(STORAGE_KEY, l);
  };

  const toggleLanguage = () => setLang(lang === "hi" ? "en" : "hi");

  const t = (key: TranslationKey): string => TRANSLATIONS[lang][key] ?? TRANSLATIONS.hi[key];

  return (
    <LanguageContext.Provider value={{ lang, t, toggleLanguage, setLang }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  return useContext(LanguageContext);
}
