uploads = []

[[generated]]
id = "uyF4uskBs2hNwpriKFkHb"
uri = "file://artifacts/mobile/assets/images/icon.png"
type = "image"
title = "raftaarride app icon"

[[outputs]]
id = "41Z-rz8ZbMm4U_s0WR1A_"
uri = "file://RaftaarRide_FullApp.tar.gz"
type = "unspecified"
title = "RaftaarRide Full App (tar.gz)"

[[outputs]]
id = "zSPSWnJMmOS5ZFIJg4CK8"
uri = "file://RaftaarRide_Complete.tar.gz"
type = "unspecified"
title = "RaftaarRide Complete Project (app + admin + backend)"

[[outputs]]
id = "4cywhCaI-ZdPE1RydSydh"
uri = "file://RaftaarRide_Admin_Panel.tar.gz"
type = "unspecified"
title = "RaftaarRide Admin Panel — Complete Source Code"

[[outputs]]
id = "sVJ3Z1slc9uPnOYEVE-M9"
uri = "file://RaftaarRide_Android_App.tar.gz"
type = "unspecified"
title = "RaftaarRide Android App — Complete Source Code"
